apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    service: {{ .Release.Name }}-svc
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-svc
  ports:
  - port: {{ .Values.deployment.flask.containerPort }}
    targetPort: {{ .Values.deployment.flask.containerPort }}
    protocol: TCP