kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-volume
  namespace: {{ .Values.namespace }}
  labels:
    type: local
    app: {{ .Release.Name }}-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi